support for journal hibernation
gazette/core pull request #411
Opened 2024-12-15 19:32 UTC by jgraettinger

2025-01-10 18:36 UTC, psFried requested changes
This looks really nice. I left a few inline comments, though IDK whether any of them should block merging. I think the docs in `overview-build-and-test.rst` could use updated before merging, though.

2025-01-10 19:03 UTC, jgraettinger commented on mainboilerplate/diagnostics.go
> +	Port    string `long:"port" env:"PORT" description:"Port for diagnostics"`
Yes, it would effectively disable diagnostics. I'll add a logged warning.

2025-01-10 20:45 UTC, jgraettinger commented on broker/append_fsm.go
> +				Offset: b.pln.spool.End,
No. At this point we don't care about the value of `suspend.Offset` (it's probably zero). The synchronization we've done up to this point guarantees that `b.pln.spool.End` is the correct next byte to be written to this journal.

This is why suspension is nominally part of the Append API -- it piggybacks on all of the synchronization machinery to ensure we're only suspending a journal at an offset agreed upon by all current replicas.

2025-01-10 20:51 UTC, jgraettinger commented on broker/append_fsm.go
> +	update.Suspend = b.nextSuspend
Added

2025-01-11 18:15 UTC, jgraettinger commented on broker/append_fsm.go
> +	case pb.AppendRequest_SUSPEND_IF_FLUSHED, pb.AppendRequest_SUSPEND_NOW:
Updated so that a SUSPENDED status is sent consistently if the journal is suspended at the completion of the current request (vs OK otherwise).

2025-01-11 18:17 UTC, jgraettinger commented
Made some lightweight updates to `overview-build-and-test.rst`, mostly removing stuff.

I backed out upgrades of gRPC, as changes there have altered memory semantics compared to its prior behavior (it now assumes it owns buffers of messages sent into SendMsg, where it hadn't before and we relied on that behavior).

2025-01-13 15:50 UTC, psFried commented on broker/protocol/protocol.proto
> +  // not set it directly. However when utilizing suspension, operators MUST
If the prior value was unsuspended and you set it to either partially or fully suspended, would the brokers handle that by either partially or fully suspending the journal?

I'm also wondering how this would work in the scenario where an older client version is running against a newer broker. The old client would presumably leave the suspend field blank, which seems like it'd effectively clobber whatever is there. We might just say not to use journal suspension unless all your clients are updated, though that does make me a little nervous because it'd be easy for someone to accidentally use an outdated `gazctl`.

I'm not really sure how important those concerns are, but I'm mainly just trying to understand what we'll need to do as part of the upgrade and what the risks are with the Apply RPC.

2025-01-13 15:53 UTC, psFried approved these changes
LGTM

2025-01-14 04:59 UTC, merged